/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Striker = IDL.Record({
  'bio' : IDL.Text,
  'club' : IDL.Text,
  'name' : IDL.Text,
  'nationality' : IDL.Text,
  'imageUrl' : IDL.Text,
  'matches' : IDL.Nat,
  'goals' : IDL.Nat,
  'position' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllStrikers' : IDL.Func([], [IDL.Vec(Striker)], ['query']),
  'getStrikerById' : IDL.Func([IDL.Text], [Striker], ['query']),
  'getTopStrikers' : IDL.Func([IDL.Nat], [IDL.Vec(Striker)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Striker = IDL.Record({
    'bio' : IDL.Text,
    'club' : IDL.Text,
    'name' : IDL.Text,
    'nationality' : IDL.Text,
    'imageUrl' : IDL.Text,
    'matches' : IDL.Nat,
    'goals' : IDL.Nat,
    'position' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllStrikers' : IDL.Func([], [IDL.Vec(Striker)], ['query']),
    'getStrikerById' : IDL.Func([IDL.Text], [Striker], ['query']),
    'getTopStrikers' : IDL.Func([IDL.Nat], [IDL.Vec(Striker)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };